version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sirf01Project
  gitServerName: sirfgit1
  gitUrl: https://github.com/sabreen786
  gitUsername: sabreen786
  gitBranch: main
- name: OnPremiseISPkg
  version: "1.0"
  gitServerName: gitrawa
  gitUrl: https://github.com/radhikaWarrierSAG
  gitUsername: radhikaWarrierSAG
  gitBranch: main
services:
- serviceName: project.sirf01.integrations:Test1
  packages:
  - name: Sirf01Project
    version: "1.0"
  - name: OnPremiseISPkg
    version: "1.0"
- serviceName: OnPremiseISPkg.loadSvc:loadData
  packages:
  - name: OnPremiseISPkg
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2015
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.jdbcTestPool.spyenabled: "false"
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.jdbcTestPool.useSSL: "false"
